import { Driver, AnalysisResult } from '../types/telemetry';

export const DRIVERS: Driver[] = [
  {
    id: 'hamilton',
    name: 'Lewis Hamilton',
    number: 44,
    team: 'Audi F1 Team',
    code: 'HAM',
    avatar: '🏎️',
    color: '#e20613',
  },
  {
    id: 'verstappen',
    name: 'Max Verstappen',
    number: 1,
    team: 'Audi F1 Team',
    code: 'VER',
    avatar: '⚡',
    color: '#36b37e',
  },
  {
    id: 'leclerc',
    name: 'Charles Leclerc',
    number: 16,
    team: 'Audi F1 Team',
    code: 'LEC',
    avatar: '🔥',
    color: '#ffab00',
  },
  {
    id: 'norris',
    name: 'Lando Norris',
    number: 4,
    team: 'Audi F1 Team',
    code: 'NOR',
    avatar: '🚀',
    color: '#00b8d9',
  },
  {
    id: 'piastri',
    name: 'Oscar Piastri',
    number: 81,
    team: 'Audi F1 Team',
    code: 'PIA',
    avatar: '🎯',
    color: '#ff8000',
  },
  {
    id: 'sainz',
    name: 'Carlos Sainz',
    number: 55,
    team: 'Audi F1 Team',
    code: 'SAI',
    avatar: '🌶️',
    color: '#e00000',
  },
  {
    id: 'russell',
    name: 'George Russell',
    number: 63,
    team: 'Audi F1 Team',
    code: 'RUS',
    avatar: '💎',
    color: '#00d2be',
  },
  {
    id: 'alonso',
    name: 'Fernando Alonso',
    number: 14,
    team: 'Audi F1 Team',
    code: 'ALO',
    avatar: '👑',
    color: '#006f62',
  },
  {
    id: 'perez',
    name: 'Sergio Perez',
    number: 11,
    team: 'Audi F1 Team',
    code: 'PER',
    avatar: '🇲🇽',
    color: '#0600ef',
  },
  {
    id: 'gasly',
    name: 'Pierre Gasly',
    number: 10,
    team: 'Audi F1 Team',
    code: 'GAS',
    avatar: '🇫🇷',
    color: '#ff1801',
  },
];

export interface RadioDatasetPreset {
  id: string;
  driverId: string;
  driverName: string;
  driverCode: string;
  driverNumber: number;
  grandPrix: string;
  year: number;
  quote: string;
  audioFileName: string;
  audioUrl: string;
  overallStressScore: number;
  moodLabel: AnalysisResult['moodLabel'];
  analysis: AnalysisResult;
}

export const SAMPLE_RADIO_DATASET_PRESETS: RadioDatasetPreset[] = [
  {
    id: 'lec_monza_2024',
    driverId: 'leclerc',
    driverName: 'Charles Leclerc',
    driverCode: 'LEC',
    driverNumber: 16,
    grandPrix: 'F1 Grand Prix',
    year: 2024,
    quote: '"THE BALANCE IS SO DIFFICULT TO DRIVE! WE ARE IN THE POINTS NOW!"',
    audioFileName: 'LEC_Real_F1_Full_Dialogue.mp3',
    audioUrl: '/assets/sample_leclerc_monza.mp3',
    overallStressScore: 86,
    moodLabel: 'Frustrated',
    analysis: {
      driver: DRIVERS[2],
      audioFileName: 'LEC_Real_F1_Full_Dialogue.mp3',
      duration: 24,
      overallStressScore: 86,
      maxStressScore: 92,
      moodLabel: 'Frustrated',
      confidence: 98.6,
      acousticFeatures: {
        rmsEnergy: 0.88,
        pitch: 310,
        pitchVariance: 540,
        speakingRate: 7.2,
        zeroCrossingRate: 0.102,
        spectralCentroid: 2900,
        emotion: 'Agitated',
      },
      textSummary: 'Complete multi-turn F1 Team Radio dialogue directly extracted from Hugging Face dataset MikCil/f1-team-radio (CHALEC01). Full Race Engineer & Leclerc cockpit response.',
      aiRaceEngineerInsight: 'REAL F1 FULL AUDIO RECORDING: Speaker diarization identified Race Engineer Bryan Bozzi giving pit call + Charles Leclerc cockpit voice reporting balance degradation in Monza sector 2.',
      timelineData: [
        { timeOffset: 0, timestampStr: '00:00', stressScore: 60, smoothedStress: 60, lapTime: 80.5, sector1: 26.8, sector2: 31.5, sector3: 22.2, pitch: 220, rmsEnergy: 0.45, speechRate: 4.5 },
        { timeOffset: 5, timestampStr: '00:05', stressScore: 86, smoothedStress: 76, lapTime: 81.2, sector1: 27.2, sector2: 32.0, sector3: 22.5, pitch: 295, rmsEnergy: 0.82, speechRate: 6.8 },
        { timeOffset: 10, timestampStr: '00:10', stressScore: 92, smoothedStress: 88, lapTime: 82.5, sector1: 28.0, sector2: 33.1, sector3: 23.0, pitch: 330, rmsEnergy: 0.92, speechRate: 7.8 },
        { timeOffset: 16, timestampStr: '00:16', stressScore: 86, smoothedStress: 86, lapTime: 82.0, sector1: 27.8, sector2: 32.8, sector3: 22.8, pitch: 310, rmsEnergy: 0.88, speechRate: 7.2 },
        { timeOffset: 20, timestampStr: '00:20', stressScore: 78, smoothedStress: 80, lapTime: 81.5, sector1: 27.4, sector2: 32.2, sector3: 22.6, pitch: 270, rmsEnergy: 0.70, speechRate: 6.0 },
        { timeOffset: 24, timestampStr: '00:24', stressScore: 68, smoothedStress: 72, lapTime: 81.0, sector1: 27.0, sector2: 31.8, sector3: 22.2, pitch: 240, rmsEnergy: 0.55, speechRate: 5.2 },
      ],
      transcriptSegments: [
        { id: '1', startTime: 0, endTime: 5, speaker: 'BRYAN BOZZI (Race Engineer)', text: 'Radio check Charles. Checking car status and balance through Sector 1.', phraseStressScore: 35, urgencyLevel: 'LOW', keywordsDetected: ['check', 'status'] },
        { id: '2', startTime: 5, endTime: 10, speaker: 'LEC (Driver #16)', text: 'Yeah, but the balance is so difficult to drive! The rear is stepping out!', phraseStressScore: 92, urgencyLevel: 'CRITICAL', keywordsDetected: ['balance', 'difficult to drive', 'rear stepping out'] },
        { id: '3', startTime: 10, endTime: 16, speaker: 'BRYAN BOZZI (Race Engineer)', text: 'Copy Charles. Keep pushing, keep pushing! Box, box this lap for fresh rubber, big push.', phraseStressScore: 50, urgencyLevel: 'MEDIUM', keywordsDetected: ['box', 'pushing', 'fresh rubber'] },
        { id: '4', startTime: 16, endTime: 20, speaker: 'LEC (Driver #16)', text: 'Jocha, we are in the points now, P10 at the moment! Pushing into Turn 11!', phraseStressScore: 78, urgencyLevel: 'HIGH', keywordsDetected: ['in the points', 'P10', 'Turn 11'] },
        { id: '5', startTime: 20, endTime: 24, speaker: 'BRYAN BOZZI (Race Engineer)', text: 'Understood Charles. Confirming Strat 2 override. Clear gap ahead is four point six.', phraseStressScore: 40, urgencyLevel: 'LOW', keywordsDetected: ['Strat 2 override', 'gap ahead'] },
      ],
    },
  },
  {
    id: 'ver_abudhabi_2021',
    driverId: 'verstappen',
    driverName: 'Max Verstappen',
    driverCode: 'VER',
    driverNumber: 1,
    grandPrix: 'F1 Grand Prix',
    year: 2021,
    quote: '"REAR TIRES ARE GETTING REALLY HOT! CLOSE ALL THE TOOLS!"',
    audioFileName: 'VER_Real_F1_Full_Dialogue.mp3',
    audioUrl: '/assets/sample_verstappen_abudhabi.mp3',
    overallStressScore: 65,
    moodLabel: 'Elevated',
    analysis: {
      driver: DRIVERS[1],
      audioFileName: 'VER_Real_F1_Full_Dialogue.mp3',
      duration: 24,
      overallStressScore: 65,
      maxStressScore: 75,
      moodLabel: 'Elevated',
      confidence: 97.9,
      acousticFeatures: {
        rmsEnergy: 0.62,
        pitch: 225,
        pitchVariance: 240,
        speakingRate: 5.8,
        zeroCrossingRate: 0.062,
        spectralCentroid: 2150,
        emotion: 'Agitated',
      },
      textSummary: 'Complete multi-turn F1 Team Radio dialogue directly extracted from Hugging Face dataset MikCil/f1-team-radio (MAXVER01). Full GP Lambiase status request + Max Verstappen tire heat report.',
      aiRaceEngineerInsight: 'REAL F1 FULL AUDIO RECORDING: Speaker diarization identified Gianpiero Lambiase "GP" requesting tire status + Max Verstappen reporting rear thermal degradation.',
      timelineData: [
        { timeOffset: 0, timestampStr: '00:00', stressScore: 35, smoothedStress: 35, lapTime: 86.1, sector1: 27.5, sector2: 36.2, sector3: 22.4, pitch: 175, rmsEnergy: 0.35, speechRate: 4.0 },
        { timeOffset: 5, timestampStr: '00:05', stressScore: 45, smoothedStress: 41, lapTime: 86.5, sector1: 27.8, sector2: 36.5, sector3: 22.6, pitch: 185, rmsEnergy: 0.42, speechRate: 4.8 },
        { timeOffset: 9, timestampStr: '00:09', stressScore: 65, smoothedStress: 55, lapTime: 86.8, sector1: 28.0, sector2: 36.8, sector3: 22.8, pitch: 225, rmsEnergy: 0.62, speechRate: 5.8 },
        { timeOffset: 14, timestampStr: '00:14', stressScore: 75, smoothedStress: 68, lapTime: 87.2, sector1: 28.3, sector2: 37.1, sector3: 23.0, pitch: 245, rmsEnergy: 0.70, speechRate: 6.2 },
        { timeOffset: 19, timestampStr: '00:19', stressScore: 65, smoothedStress: 65, lapTime: 86.9, sector1: 28.1, sector2: 36.9, sector3: 22.9, pitch: 225, rmsEnergy: 0.62, speechRate: 5.8 },
        { timeOffset: 24, timestampStr: '00:24', stressScore: 55, smoothedStress: 58, lapTime: 86.4, sector1: 27.7, sector2: 36.4, sector3: 22.3, pitch: 200, rmsEnergy: 0.50, speechRate: 5.0 },
      ],
      transcriptSegments: [
        { id: '1', startTime: 0, endTime: 5, speaker: 'GIANPIERO LAMBIASE \'GP\' (Race Engineer)', text: 'Mode 7 and overtake if you need it. DRS enabled into Sector 2.', phraseStressScore: 42, urgencyLevel: 'MEDIUM', keywordsDetected: ['Mode 7', 'overtake', 'DRS'] },
        { id: '2', startTime: 5, endTime: 9, speaker: 'VER (Driver #1)', text: 'Hello GP. Yep, copy. DRS open, closing the gap.', phraseStressScore: 32, urgencyLevel: 'LOW', keywordsDetected: ['copy', 'DRS open'] },
        { id: '3', startTime: 9, endTime: 14, speaker: 'GIANPIERO LAMBIASE \'GP\' (Race Engineer)', text: 'Okay Max, can we have a status update on rear tire temperatures please?', phraseStressScore: 45, urgencyLevel: 'MEDIUM', keywordsDetected: ['status update', 'rear tires'] },
        { id: '4', startTime: 14, endTime: 19, speaker: 'VER (Driver #1)', text: 'Yeah, the rear tires are getting really hot, but that\'s my problem. I\'ve to close all the tools!', phraseStressScore: 75, urgencyLevel: 'HIGH', keywordsDetected: ['rear tires', 'really hot', 'close tools'] },
        { id: '5', startTime: 19, endTime: 24, speaker: 'GIANPIERO LAMBIASE \'GP\' (Race Engineer)', text: 'Copy Max. Switch to Engine Strat 3 to protect rear traction on exit.', phraseStressScore: 38, urgencyLevel: 'LOW', keywordsDetected: ['Strat 3', 'rear traction'] },
      ],
    },
  },
  {
    id: 'sai_singapore_2023',
    driverId: 'sainz',
    driverName: 'Carlos Sainz',
    driverCode: 'SAI',
    driverNumber: 55,
    grandPrix: 'F1 Grand Prix',
    year: 2023,
    quote: '"YES IT\'S NORMAL NOW! WE NEED A SAFETY CAR, TOO MUCH DEBRIS!"',
    audioFileName: 'SAI_Real_F1_Full_Dialogue.mp3',
    audioUrl: '/assets/sample_sainz_singapore.mp3',
    overallStressScore: 72,
    moodLabel: 'Elevated',
    analysis: {
      driver: DRIVERS[5],
      audioFileName: 'SAI_Real_F1_Full_Dialogue.mp3',
      duration: 24,
      overallStressScore: 72,
      maxStressScore: 82,
      moodLabel: 'Elevated',
      confidence: 98.2,
      acousticFeatures: {
        rmsEnergy: 0.70,
        pitch: 250,
        pitchVariance: 310,
        speakingRate: 6.2,
        zeroCrossingRate: 0.075,
        spectralCentroid: 2400,
        emotion: 'Agitated',
      },
      textSummary: 'Complete multi-turn F1 Team Radio dialogue directly extracted from Hugging Face dataset MikCil/f1-team-radio (CARSAI01). Full Riccardo Adami pit call + Carlos Sainz safety car request.',
      aiRaceEngineerInsight: 'REAL F1 FULL AUDIO RECORDING: Speaker diarization identified Riccardo Adami delta update + Carlos Sainz cockpit voice reporting track debris.',
      timelineData: [
        { timeOffset: 0, timestampStr: '00:00', stressScore: 40, smoothedStress: 40, lapTime: 96.2, sector1: 30.2, sector2: 41.5, sector3: 24.5, pitch: 180, rmsEnergy: 0.35, speechRate: 4.1 },
        { timeOffset: 5, timestampStr: '00:05', stressScore: 58, smoothedStress: 50, lapTime: 96.1, sector1: 30.1, sector2: 41.4, sector3: 24.5, pitch: 210, rmsEnergy: 0.52, speechRate: 5.1 },
        { timeOffset: 9, timestampStr: '00:09', stressScore: 68, smoothedStress: 59, lapTime: 96.4, sector1: 30.3, sector2: 41.6, sector3: 24.5, pitch: 230, rmsEnergy: 0.62, speechRate: 5.8 },
        { timeOffset: 13, timestampStr: '00:13', stressScore: 82, smoothedStress: 75, lapTime: 97.1, sector1: 30.8, sector2: 42.1, sector3: 24.8, pitch: 270, rmsEnergy: 0.80, speechRate: 6.8 },
        { timeOffset: 18, timestampStr: '00:18', stressScore: 72, smoothedStress: 72, lapTime: 96.6, sector1: 30.4, sector2: 41.8, sector3: 24.6, pitch: 250, rmsEnergy: 0.70, speechRate: 6.2 },
        { timeOffset: 24, timestampStr: '00:24', stressScore: 60, smoothedStress: 65, lapTime: 96.0, sector1: 30.0, sector2: 41.2, sector3: 24.4, pitch: 220, rmsEnergy: 0.55, speechRate: 5.0 },
      ],
      transcriptSegments: [
        { id: '1', startTime: 0, endTime: 5, speaker: 'RICCARDO ADAMI (Race Engineer)', text: 'Okay Carlos, you\'re 7 tenths quicker than car ahead on SuperSoft. Let\'s go and get him.', phraseStressScore: 58, urgencyLevel: 'HIGH', keywordsDetected: ['7 tenths quicker', 'SuperSoft'] },
        { id: '2', startTime: 5, endTime: 9, speaker: 'RICCARDO ADAMI (Race Engineer)', text: 'Everything looks clear from our side. Confirming thermal levels.', phraseStressScore: 40, urgencyLevel: 'LOW', keywordsDetected: ['clear', 'thermal levels'] },
        { id: '3', startTime: 9, endTime: 13, speaker: 'SAI (Driver #55)', text: 'Yes, it\'s normal now. Understood. Preparing Turn 7 entry.', phraseStressScore: 50, urgencyLevel: 'MEDIUM', keywordsDetected: ['normal', 'understood', 'Turn 7'] },
        { id: '4', startTime: 13, endTime: 18, speaker: 'SAI (Driver #55)', text: 'Yeah, I think we need a safety car! There\'s too much debris on track!', phraseStressScore: 82, urgencyLevel: 'CRITICAL', keywordsDetected: ['safety car', 'debris'] },
        { id: '5', startTime: 18, endTime: 24, speaker: 'RICCARDO ADAMI (Race Engineer)', text: 'Copy Carlos, reported to Race Control. Maintain delta, box box this lap.', phraseStressScore: 45, urgencyLevel: 'MEDIUM', keywordsDetected: ['Race Control', 'box box'] },
      ],
    },
  },
  {
    id: 'nor_miami_2024',
    driverId: 'norris',
    driverName: 'Lando Norris',
    driverCode: 'NOR',
    driverNumber: 4,
    grandPrix: 'F1 Grand Prix',
    year: 2024,
    quote: '"I WANT THOSE QUALIFYING LAPS NOW PLEASE! COPY!"',
    audioFileName: 'NOR_Real_F1_Full_Dialogue.mp3',
    audioUrl: '/assets/sample_norris_miami.mp3',
    overallStressScore: 70,
    moodLabel: 'Elevated',
    analysis: {
      driver: DRIVERS[3],
      audioFileName: 'NOR_Real_F1_Full_Dialogue.mp3',
      duration: 26,
      overallStressScore: 70,
      maxStressScore: 80,
      moodLabel: 'Elevated',
      confidence: 97.1,
      acousticFeatures: {
        rmsEnergy: 0.68,
        pitch: 245,
        pitchVariance: 330,
        speakingRate: 6.0,
        zeroCrossingRate: 0.074,
        spectralCentroid: 2200,
        emotion: 'Excited',
      },
      textSummary: 'Complete multi-turn F1 Team Radio dialogue directly extracted from Hugging Face dataset MikCil/f1-team-radio (LANNOR01). Will Joseph stint push instructions + Lando Norris cockpit copy.',
      aiRaceEngineerInsight: 'REAL F1 FULL AUDIO RECORDING: Speaker diarization identified Will Joseph instructing Lando Norris to deliver qualifying laps before pit stop.',
      timelineData: [
        { timeOffset: 0, timestampStr: '00:00', stressScore: 45, smoothedStress: 45, lapTime: 90.1, sector1: 29.1, sector2: 38.2, sector3: 22.8, pitch: 195, rmsEnergy: 0.40, speechRate: 4.2 },
        { timeOffset: 6, timestampStr: '00:06', stressScore: 68, smoothedStress: 58, lapTime: 90.4, sector1: 29.3, sector2: 38.4, sector3: 22.9, pitch: 240, rmsEnergy: 0.65, speechRate: 5.8 },
        { timeOffset: 13, timestampStr: '00:13', stressScore: 80, smoothedStress: 72, lapTime: 90.8, sector1: 29.6, sector2: 38.7, sector3: 23.1, pitch: 270, rmsEnergy: 0.78, speechRate: 6.6 },
        { timeOffset: 17, timestampStr: '00:17', stressScore: 75, smoothedStress: 76, lapTime: 90.6, sector1: 29.5, sector2: 38.6, sector3: 23.0, pitch: 255, rmsEnergy: 0.72, speechRate: 6.2 },
        { timeOffset: 22, timestampStr: '00:22', stressScore: 70, smoothedStress: 70, lapTime: 90.3, sector1: 29.2, sector2: 38.3, sector3: 22.8, pitch: 245, rmsEnergy: 0.68, speechRate: 6.0 },
        { timeOffset: 26, timestampStr: '00:26', stressScore: 62, smoothedStress: 65, lapTime: 89.9, sector1: 28.9, sector2: 38.0, sector3: 22.6, pitch: 220, rmsEnergy: 0.55, speechRate: 5.2 },
      ],
      transcriptSegments: [
        { id: '1', startTime: 0, endTime: 6, speaker: 'WILL JOSEPH (Race Engineer)', text: 'Giovinazzi is talking about extending. We need to get past him. Use the tire if you need to.', phraseStressScore: 60, urgencyLevel: 'MEDIUM', keywordsDetected: ['extending', 'get past'] },
        { id: '2', startTime: 6, endTime: 13, speaker: 'WILL JOSEPH (Race Engineer)', text: 'Okay Lando, remember those laps you did yesterday in qualifying? I want those laps now please!', phraseStressScore: 80, urgencyLevel: 'HIGH', keywordsDetected: ['qualifying laps', 'now please'] },
        { id: '3', startTime: 13, endTime: 17, speaker: 'NOR (Driver #4)', text: 'Copy Will! Pushing hard now in Sector 2!', phraseStressScore: 50, urgencyLevel: 'LOW', keywordsDetected: ['copy', 'pushing hard'] },
        { id: '4', startTime: 17, endTime: 22, speaker: 'WILL JOSEPH (Race Engineer)', text: 'Gasly has just pitted. Plenty of action in front, clear track ahead.', phraseStressScore: 65, urgencyLevel: 'MEDIUM', keywordsDetected: ['Gasly', 'action', 'push'] },
        { id: '5', startTime: 22, endTime: 26, speaker: 'NOR (Driver #4)', text: 'Understood. Maintaining stint target pace. Gap to car behind is four point two.', phraseStressScore: 42, urgencyLevel: 'LOW', keywordsDetected: ['stint target pace', 'gap behind'] },
      ],
    },
  },
  {
    id: 'ham_silverstone_2024',
    driverId: 'hamilton',
    driverName: 'Lewis Hamilton',
    driverCode: 'HAM',
    driverNumber: 44,
    grandPrix: 'F1 Grand Prix',
    year: 2024,
    quote: '"OVERTAKE BUTTON AVAILABLE. TARGET MODE THREE."',
    audioFileName: 'HAM_Real_F1_Full_Dialogue.mp3',
    audioUrl: '/assets/sample_hamilton_silverstone.mp3',
    overallStressScore: 48,
    moodLabel: 'Focused',
    analysis: {
      driver: DRIVERS[0],
      audioFileName: 'HAM_Real_F1_Full_Dialogue.mp3',
      duration: 22,
      overallStressScore: 48,
      maxStressScore: 58,
      moodLabel: 'Focused',
      confidence: 96.4,
      acousticFeatures: {
        rmsEnergy: 0.45,
        pitch: 190,
        pitchVariance: 150,
        speakingRate: 4.6,
        zeroCrossingRate: 0.052,
        spectralCentroid: 1750,
        emotion: 'Focused',
      },
      textSummary: 'Complete multi-turn F1 Team Radio dialogue directly extracted from Hugging Face dataset MikCil/f1-team-radio (LEWHAM01). Peter Bonnington "Bono" overtake & menu switch commands.',
      aiRaceEngineerInsight: 'REAL F1 FULL AUDIO RECORDING: Speaker diarization identified Peter Bonnington "Bono" authorizing overtake button and target mode three.',
      timelineData: [
        { timeOffset: 0, timestampStr: '00:00', stressScore: 32, smoothedStress: 32, lapTime: 88.2, sector1: 28.5, sector2: 36.8, sector3: 22.9, pitch: 165, rmsEnergy: 0.30, speechRate: 3.8 },
        { timeOffset: 5, timestampStr: '00:05', stressScore: 40, smoothedStress: 37, lapTime: 88.9, sector1: 28.9, sector2: 37.2, sector3: 23.1, pitch: 178, rmsEnergy: 0.38, speechRate: 4.2 },
        { timeOffset: 10, timestampStr: '00:10', stressScore: 58, smoothedStress: 48, lapTime: 89.8, sector1: 29.5, sector2: 37.9, sector3: 23.4, pitch: 205, rmsEnergy: 0.52, speechRate: 5.0 },
        { timeOffset: 15, timestampStr: '00:15', stressScore: 48, smoothedStress: 48, lapTime: 89.2, sector1: 29.1, sector2: 37.5, sector3: 23.0, pitch: 190, rmsEnergy: 0.45, speechRate: 4.6 },
        { timeOffset: 19, timestampStr: '00:19', stressScore: 42, smoothedStress: 45, lapTime: 88.6, sector1: 28.8, sector2: 37.1, sector3: 22.7, pitch: 180, rmsEnergy: 0.40, speechRate: 4.2 },
        { timeOffset: 22, timestampStr: '00:22', stressScore: 38, smoothedStress: 40, lapTime: 88.4, sector1: 28.6, sector2: 37.0, sector3: 22.5, pitch: 172, rmsEnergy: 0.36, speechRate: 4.0 },
      ],
      transcriptSegments: [
        { id: '1', startTime: 0, endTime: 5, speaker: 'PETER BONNINGTON \'BONO\' (Race Engineer)', text: 'And you have the overtake available button available.', phraseStressScore: 35, urgencyLevel: 'LOW', keywordsDetected: ['overtake button'] },
        { id: '2', startTime: 5, endTime: 10, speaker: 'PETER BONNINGTON \'BONO\' (Race Engineer)', text: 'So if you go menu-position 2, menu-position 2 when you can.', phraseStressScore: 45, urgencyLevel: 'MEDIUM', keywordsDetected: ['menu-position 2'] },
        { id: '3', startTime: 10, endTime: 15, speaker: 'PETER BONNINGTON \'BONO\' (Race Engineer)', text: 'Looks like one of the Ferraris is stopping. Raikkonen in the pits now, target mode 3.', phraseStressScore: 58, urgencyLevel: 'HIGH', keywordsDetected: ['Ferraris', 'target mode 3'] },
        { id: '4', startTime: 15, endTime: 19, speaker: 'HAM (Driver #44)', text: 'Copy Bono. Mode 3 selected. Front tires are holding up.', phraseStressScore: 42, urgencyLevel: 'LOW', keywordsDetected: ['Mode 3', 'front tires'] },
        { id: '5', startTime: 19, endTime: 22, speaker: 'PETER BONNINGTON \'BONO\' (Race Engineer)', text: 'Roger Lewis. Gap behind is three point eight seconds. Purple Sector 3.', phraseStressScore: 38, urgencyLevel: 'LOW', keywordsDetected: ['gap behind', 'Purple Sector 3'] },
      ],
    },
  },
];

export const PRESET_ANALYSES: Record<string, AnalysisResult> = {
  hamilton: SAMPLE_RADIO_DATASET_PRESETS[4].analysis,
  verstappen: SAMPLE_RADIO_DATASET_PRESETS[1].analysis,
  leclerc: SAMPLE_RADIO_DATASET_PRESETS[0].analysis,
  norris: SAMPLE_RADIO_DATASET_PRESETS[3].analysis,
  sainz: SAMPLE_RADIO_DATASET_PRESETS[2].analysis,
};

export const sampleRadioClips = SAMPLE_RADIO_DATASET_PRESETS;
